### ISSUE TITLE
'plan.tasks.send_idea_notification' has no attribute 'delay'

### ISSUE THREAD

**Issue by giusepp3palumbo** [f1nnix/magplan#73]
When I try to suggest a new Idea, i get the following error:
`AttributeError: module 'plan.tasks.send_idea_notification' has no attribute 'delay'`

It seems this method doesn't exist, i try to search it without success

**Comment by f1nnix** [comment]
Thank you, there was a bug in import statement from recent changes. Fixed.

plan.tasks.send_idea_notification should not have any searchable attribute delay. It's bound via `shared_task` decorator via Celery.
